title: "Internal Audit & Analytics Portfolio"
description: "Colby Kellersberger, CIA, CFE â€” Internal Audit Manager building audit tools, analytics, and Python apps."

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown

url: "https://colby-k.github.io"
baseurl: "/portfolio-cayman-test"
